packaging_format = 2

id = "manyfold"
name = "Manyfold"
description.en = "An open source, self-hosted web application for managing a collection of 3d models, particularly focused on 3d printing."

version = "v0.136.0~ynh1"

maintainers = [@davefp]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://manyfold.app/"
demo = "https://try.manyfold.app/"
admindoc = "https://manyfold.app/sysadmin/"
userdoc = "https://manyfold.app/manual/"
code = "https://github.com/manyfold3d/manyfold"
cpe = "cpe:2.3:a:manyfold:manyfold"
fund = "https://opencollective.com/manyfold/donate"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "2G" # TODO: confirm this
ram.build = "1G" # TODO: confirm this
ram.runtime = "500M" # TODO: confirm this

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.federation]
    type = "string"
    ask.en = "Enable federation?"
    help.en = "Turn on cross-server ActivityPub federation features such as remote following, webfinger discovery, etc."
    choices.enabled = "Yes"
    choices.disabled = "No"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/manyfold3d/manyfold/archive/refs/tags/v0.136.0.tar.gz"
        sha256 = "2b3db3fbcb8a3ad324aefa79ae60da699dec7aa101f802838d5b653ef92f4873"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    web.default = 3000

    [resources.apt]
    packages = "libarchive13 imagemagick libassimp-dev"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"

    [resources.ruby]
    version = "3.4.8"
